### ISSUE TITLE
Admin plugin

### ISSUE THREAD

**Issue by nado** [nado/go-b0tsec#1]
Plugin to enable/disable plugins while the bot is running like `!plugins +yt -ddg +title`

**Comment by depado** [comment]
Seems like a tricky one actually. There will be the need to check for admin rights, querying the server directly for the nickname who is performing the request. This can't be achieved with a plugin (plugins don't expect responses)
More like something in the core.

**Comment by nado** [comment]
Alright, I haven’t thought a lot about this yet, this issue was more like a reminder to me, but you are right.

**Comment by nado** [comment]
https://github.com/nado/go-b0tsec/commit/2715a865c3f3832e7e42565c9288d4f2e4f9a791 is a first step towards dynamic plugins (de)activation

**Comment by depado** [comment]
Very nice :)

**Comment by nado** [comment]
https://github.com/nado/go-b0tsec/commit/2a74fb537f2bcfe08f0655420d7497b53aae2d7c plugins are fully managed with this commit.
